### PR TITLE
Update disease_ontology.yaml

### PR DESCRIPTION
**Pull request by mcarlsn**
Fixed 2 typos on lines 215-216 and 229.

### CODE REVIEW

**Comment by mcarlsn** [comment]
hi hi I hope that you're doing well. If you have a chance, hoping you can merge this relatively soon - I would like this file as part of a project. Thank you, Ethan!

**Comment by lwaldron** [comment]
Good catches, thank you @mcarlsn !

**Comment by mcarlsn** [comment]
Thank you, Ethan! And @lwaldron I can't take full credit re: Sean and Sehyun :)

**Comment by Ethan-Loo** [comment]
The file was rebased and merged. Hope that helps to know in the case of tracking updates. Best of luck with your projects! 

As a side note, I plan to update the readme soon to request citations for external use of this repo beyond the Waldron lab.

**Comment by mcarlsn** [comment]
Amazing - thank you for the update!

**Pull request merged**
